analytics/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import verify_jwt_token

from . import views
from .view_controllers import index
from .view_controllers import dashboard
from .view_controllers import report_exports
from .view_controllers import saveForms
from .view_controllers import loginAPI

app_name = 'analytics'

# router = routers.DefaultRouter()
# router.register(r'', dashboard.DashboardViewSet, basename='get-details')

router = routers.DefaultRouter()
router.register(r'add_task', views.Add_task, basename='add_task')
router.register(r'update-graph-config', views.Update_graph, basename='update-graph-config')
router.register(r'post-request', saveForms.postRequestViewSet, basename='post-request')
router.register(r'get-reports', dashboard.GetReportsViewSet, basename='get-reports')
router.register(r'add_to_report', index.addToReportViewSet, basename='add_to_report')
router.register(r'save_notes', index.saveNotesViewSet, basename='save_notes')
router.register(r'save_report_structure', index.updateReportViewSet, basename='save_report_structure')
# router.register(r'authenticate-user', loginAPI.loginViewSet_s, basename='authenticate-user')

urlpatterns = [
    path('', index.index, name='index'),
    path('api/', include(router.urls)),
    # path('authenticate-user/', include('rest_auth.urls')),
    # path('update/', include(router.urls)),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('add_task', views.add_task, name='add_task'),
    path('dashboard', index.dashboard, name='dashboard'),
    path('documentation', index.documentation, name='documentation'),
    path('admin-documentation', index.admin_documentation, name='admin-documentation'),
    path('inputter-documentation', index.inputter_documentation, name='inputter-documentation'),
    path('login', index.login, name='login'),
    path('logout', index.logout_user, name='logout'),
    path('media', index.media, name='media'),
    path('add_folder', index.add_folder, name='add_folder'),
    path('add_to_folder', index.add_to_folder, name='add_to_folder'),
    path('add_to_report', index.add_to_report, name='add_to_report'),
    path('delete_images', index.delete_images, name='delete_images'),
    path('delete_folder', index.delete_folder, name='delete_folder'),
    path('delete_graph', index.delete_graph, name='delete_graph'),
    path('delete_table', index.delete_table, name='delete_table'),
    path('save_graph', index.save_graph, name='save_graph'),
    path('graph-builder', index.graph_builder, name='graph-builder'),
    path('report-builder', index.report_builder, name='report-builder'),
    path('table-builder', index.table_builder, name='table-builder'),
    path('get-tables/', dashboard.GetTablesViewSet.as_view(), name='get-tables'),
    path('get-table/', dashboard.GetTableViewSet.as_view({'get': 'retrieve'}), name='get-table'),
    path('get-report/', dashboard.GetReportViewSet.as_view({'get': 'retrieve'}), name='get-report'),
    path('get-notes/', dashboard.GetNotesViewSet.as_view({'get': 'retrieve'}), name='get-notes'),
    path('component_values',views.component_values, name='component_values'),
    path('reports',views.reports_f, name='reports'),
    path('graphs',views.graphs, name='graphs'),
    path('tables',views.tables, name='tables'),
    path('view-graph', views.GetUsers.as_view(), name='view-graph'),
    path('view_table/<module>/<report_id>/',views.view_table, name='view_table'),
    path('view_report/<report_id>/',views.view_report, name='view_report'),
    path('view_all_reports/<module>/',views.view_all_reports, name='view_all_reports'),
    path('register_user', index.registerUser, name='register_user'),
    path('add-user', index.adduser, name='add-user'),
    path('add_report', index.add_report, name='add_report'),
    path('edit-user', index.edituser, name='edit-user'),
    path('schedule_task', index.adduser, name='schedule_task'),
    path('get-details/', dashboard.DashboardViewSet.as_view(), name='get-details'),
    path('get-notifications/', dashboard.NotificationsViewSet.as_view(), name='get-notifications'),
    path('get-users/', views.GetUsers.as_view(), name='get-users'),
    path('/dataProcessor/',include('dataProcessor.urls')),
    path('get-module-details/', dashboard.buildGraphViewSet.as_view(), name='get-module-details'),
    path('get-modules/', index.getModulesViewSet.as_view({'get': 'retrieve'}), name='get-modules'),
    path('get-reports/', dashboard.GetReportsViewSet.as_view({'get': 'retrieve'}), name='get-reports'),
    path('post-request/', saveForms.postRequestViewSet, name='post-request'),
    path('download-documentation/', index.download_pdf_file, name='download-documentation'),
    path('authenticate-user/login/', loginAPI.loginViewSet_s.as_view(), name='authenticate-user'),
    # path(r'^export/csv$', report_exports.export_single_report, name='export_report'),
    path(r'^export/csv/$', report_exports.export_report, name='export_report'),
    path(r'authenticate-user/user/login/', obtain_jwt_token),
    path(r'api-token-verify/', verify_jwt_token),
]

dataAnalytics/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from rest_framework.authtoken.views import obtain_auth_token

from . import view

urlpatterns = [
    path('', view.index, name='index'),
	path('analytics/', include('analytics.urls')),
	path('dataProcessor/',include('dataProcessor.urls')),
    path('api/',include('dataProcessor.urls')),
    path('update/',include('analytics.urls')),
    path(r'^admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth')
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

dataProcessor/routers/urls.py
from django.urls import path
from rest_framework import routers

from . import views
from .view_controllers import index

dataProcessor/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views
from .view_controllers import Storage_facility
from .view_controllers import Grease_and_hydrogen
from .view_controllers import Waste_management
from .view_controllers import Inceneration
from .view_controllers import Liquid_waste_oil
from .view_controllers import Health_and_hygiene
from .view_controllers import Energy_management
from .view_controllers import Water_management
from .view_controllers import Complaints_register
from .view_controllers import Slope_stabilization_and_surface_water_retention
from .view_controllers import Safety_training
from .view_controllers import Safety_permission_system
from .view_controllers import Safety_tools
from .view_controllers import ImageUploader
from .view_controllers import geo_reference
from .view_controllers import FuelFarm
from .view_controllers import WorkEnvCompliance
from .view_controllers import Warehouse
from .view_controllers import Conveyers
from .view_controllers import IncidentReport
from analytics.view_controllers import formulate_report
from .view_controllers import index

app_name = 'dataProcessor'

router = routers.DefaultRouter()
router.register(r'add-seepage', Storage_facility.Storage_facilityViewSet, basename='add-seepage')
router.register(r'add-grease-and-hydrocarbon', Grease_and_hydrogen.Grease_and_hydrogenViewSet, basename='add-grease-and-hydrocarbon')
router.register(r'add-waste-management', Waste_management.Waste_managementViewSet, basename='add-waste-management')
router.register(r'add-inceneration', Inceneration.IncenerationViewSet, basename='add-inceneration')
router.register(r'add-liquid-waste-oil', Liquid_waste_oil.liquid_waste_oilViewSet, basename='add-liquid-waste-oil')
router.register(r'add-health-and-hygiene-awareness', Health_and_hygiene.Health_and_hygieneViewSet, basename='add-health-and-hygiene-awareness')
router.register(r'add-energy-management', Energy_management.Energy_managementViewSet, basename='add-energy-management')
router.register(r'add-water-management', Water_management.Water_managementViewSet, basename='add-water-management')
router.register(r'add-complaints-register', Complaints_register.Complaints_registerViewSet, basename='add-complaints-register')
router.register(r'add-slope-stabilization', Slope_stabilization_and_surface_water_retention.Slope_stabilization_and_surface_water_retentionViewSet, basename='add-slope-stabilization')
router.register(r'add-safety-training', Safety_training.Safety_trainingViewSet, basename='add-safety-training')
router.register(r'add-safety-permission-system', Safety_permission_system.Safety_permission_systemViewSet, basename='add-safety-permission-system')
router.register(r'add-safety-tools', Safety_tools.Safety_toolsViewSet, basename='add-safety-tools')
router.register(r'add-reference-point', geo_reference.Geo_referenceViewSet, basename='add-reference-point')
router.register(r'add-fuel-farm-data', FuelFarm.FuelFarmViewSet, basename='add-fuel-farm-data')
router.register(r'add-work-environmental-compliance-data', WorkEnvCompliance.WorkEnvComplianceViewSet, basename='add-work-environmental-compliance-data')
router.register(r'add-warehouse-data', Warehouse.WarehouseViewSet, basename='add-warehouse-data')
router.register(r'add-conveyers-data', Conveyers.ConveyersViewSet, basename='add-conveyers-data')
router.register(r'add-incident-report', IncidentReport.IncidentReportViewSet, basename='add-incident-report')
router.register(r'build-table', formulate_report.formulateReportViewSet, basename='build-table')
router.register(r'save-table', formulate_report.saveTableViewSet, basename='save-table')
router.register(r'upload_image', ImageUploader.ImageUploader, basename='upload_image')


urlpatterns = [
    path('', index.index, name='index'),
    path('add/', include(router.urls)),
    path('get_template/<module>/',views.get_template, name='get_template'),
    path('grease-and-hydrocarbon', views.grease_and_hydrocarbonView, name='grease-and-hydrocarbon'),
    path('waste-management', views.waste_managementView, name='waste-management'),
    path('inceneration', views.incenerationView, name='inceneration'),
    path('liquid-waste-oil', views.liquid_waste_oilView, name='liquid-waste-oil'),
    path('health-and-hygiene-awareness', views.health_and_hygiene_awarenessView, name='health-and-hygiene-awareness'),
    path('energy-management', views.energy_managementView, name='energy-management'),
    path('water-management', views.water_managementView, name='water-management'),
    path('complaints-register', views.complaints_registerView, name='complaints-register'),
    path('slope-stabilization', views.slope_stabilizationView, name='slope-stabilization'),
    path('safety-training', views.safety_trainingView, name='safety-training'),
    path('safety-permission-system', views.safety_permission_systemView, name='safety-permission-system'),
    path('safety-tools', views.safety_toolsView, name='safety-tools'),
    path('storage-facility', views.storage_facilityView, name='storage-facility'),
    path('geo-reference', views.geoReferenceView, name='geo-reference'),
    path('fuel-farm', views.fuelFarmView, name='fuel-farm'),
    path('work-environment-compliance', views.workEnvComplianceView, name='work-environment-compliance'),
    path('warehouse', views.warehouseView, name='warehouse'),
    path('conveyers', views.conveyersView, name='conveyers'),
    path('incident-report', views.incidentReportView, name='incident-report'),
    # path('/analytics/',include('analytics.urls')),
    # path('add', views.Storage_facilityViewSet, name='add'),
]


# urlpatterns += router.urls

dataProcessor/models.py
from django.db import models

# Create your models here.

dataProcessor/templates/dataProcessor/calendar.html
{% load static %}
<aside id="sidebar-right" class="sidebar-right">
				<div class="nano">
					<div class="nano-content">
						<a href="#" class="mobile-close visible-xs">
							Collapse <i class="fa fa-chevron-right"></i>
						</a>
			
						<div class="sidebar-right-wrapper">
			
							<div class="sidebar-widget widget-calendar">
								<h6>Upcoming Tasks</h6>
								<div data-plugin-datepicker data-plugin-skin="dark" ></div>
			
								<ul>
									<li>
										<time datetime="2014-04-19T00:00+00:00">04/19/2014</time>
										<span>Company Meeting</span>
									</li>
								</ul>
							</div>
			
							<div class="sidebar-widget widget-friends">
								<h6>Tasks</h6>
								<ul>
									<!-- <li class="status-online">
										<figure class="profile-picture">
											<img src="{% static 'dataProcessor/assets/images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
										</figure>
										<div class="profile-info">
											<span class="name">Joseph Doe Junior</span>
											<span class="title">Hey, how are you?</span>
										</div>
									</li>
									<li class="status-online">
										<figure class="profile-picture">
											<img src="{% static 'dataProcessor/assets/images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
										</figure>
										<div class="profile-info">
											<span class="name">Joseph Doe Junior</span>
											<span class="title">Hey, how are you?</span>
										</div>
									</li>
									<li class="status-offline">
										<figure class="profile-picture">
											<img src="{% static 'analytics/assets/images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
										</figure>
										<div class="profile-info">
											<span class="name">Joseph Doe Junior</span>
											<span class="title">Hey, how are you?</span>
										</div>
									</li>
									<li class="status-offline">
										<figure class="profile-picture">
											<img src="{% static 'analytics/assets/images/!sample-user.jpg' %}" alt="Joseph Doe" class="img-circle">
										</figure>
										<div class="profile-info">
											<span class="name">Joseph Doe Junior</span>
											<span class="title">Hey, how are you?</span>
										</div>
									</li> -->
								</ul>
							</div>
			
						</div>
					</div>
				</div>
			</aside>

dataProcessor/templates/dataProcessor/footer.html
{% load static %}
<footer>
		<script src="{% static 'analytics/assets/vendor/jquery/jquery.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/bootstrap/js/bootstrap.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/nanoscroller/nanoscroller.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/magnific-popup/magnific-popup.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>
		
		<script src="{% static 'analytics/assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jquery-appear/jquery.appear.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jquery-easypiechart/jquery.easypiechart.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/flot/jquery.flot.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/flot-tooltip/jquery.flot.tooltip.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/flot/jquery.flot.pie.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/flot/jquery.flot.categories.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/flot/jquery.flot.resize.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jquery-sparkline/jquery.sparkline.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/raphael/raphael.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/morris/morris.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/gauge/gauge.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/snap-svg/snap.svg.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/liquid-meter/liquid.meter.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/jquery.vmap.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/data/jquery.vmap.sampledata.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/maps/jquery.vmap.world.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/maps/continents/jquery.vmap.africa.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/maps/continents/jquery.vmap.asia.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/maps/continents/jquery.vmap.australia.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/maps/continents/jquery.vmap.europe.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/maps/continents/jquery.vmap.north-america.js' %}"></script>
		<script src="{% static 'analytics/assets/vendor/jqvmap/maps/continents/jquery.vmap.south-america.js' %}"></script>
		

		<script src="{% static 'analytics/assets/javascripts/theme.js' %}"></script>
		

		<script src="{% static 'analytics/assets/javascripts/theme.custom.js' %}"></script>
		

		<script src="{% static 'analytics/assets/javascripts/theme.init.js' %}"></script>
</footer>
</html>

dataProcessor/templates/dataProcessor/head.html
{% load static %}

<!DOCTYPE html>
<html class="fixed">
<head>

		<!-- Basic -->
		<meta charset="UTF-8">

		<title>Environmental Report</title>
		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="JSOFT Admin - Responsive HTML5 Template">
		<meta name="author" content="JSOFT.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<link rel="stylesheet" href="{% static 'analytics/bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'dataProcessor/css/dataProcessor.css' %}">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="{% static 'analytics/assets/vendor/bootstrap/css/bootstrap.css' %}" />
		<link rel="stylesheet" href="{% static 'analytics/assets/vendor/font-awesome/css/font-awesome.css' %}" />
		<link rel="stylesheet" href="{% static 'analytics/assets/vendor/magnific-popup/magnific-popup.css' %}" />
		<link rel="stylesheet" href="{% static 'analytics/assets/vendor/bootstrap-datepicker/css/datepicker3.css' %}" />

		<!-- Specific Page Vendor CSS -->
		<link rel="stylesheet" href="{% static 'analytics/assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css' %}" />
		<link rel="stylesheet" href="{% static 'analytics/assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css' %}" />
		<link rel="stylesheet" href="{% static 'analytics/assets/vendor/morris/morris.css' %}" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="{% static 'analytics/assets/stylesheets/theme.css' %}" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="{% static 'analytics/assets/stylesheets/skins/default.css' %}" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="{% static 'analytics/assets/stylesheets/theme-custom.css' %}">

		<!-- Head Libs -->
		<script src="{% static 'analytics/assets/vendor/modernizr/modernizr.js' %}"></script>

		<link rel="stylesheet" type="text/css" href="{% static 'analytics/css/analyticsAdmin.css' %}">

		<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
	<script src="{% static 'analytics/js/jquery-3.2.1.js' %}"></script>
	<script src="https://kit.fontawesome.com/967d61a618.js" crossorigin="anonymous"></script>
</head>
<!-- <header>
	<nav class="navbar navbar-icon-top navbar-expand-lg bg-dark navbar-dark">

		<a class="navbar-brand" href="{% url 'dataProcessor:index' %}">Navbar</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <input type="hidden" name="sub-category-type" id="sub-cateogory-type" value="">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item  position-static mx-4">
          <a href="{% url 'dataProcessor:index' %}" class="btn btn-link" id="navbarDropdown" aria-haspopup="true" aria-expanded="false">
            Home
          </a>
      </li>
      <li class="nav-item mx-4">
        <a class="nav-link" href="{% url 'analytics:dashboard' %}">
          Dashboard
        </a>
      </li>
      <li class="nav-item mx-4">
        <a class="nav-link" href="#">
          get data test
        </a>
      </li>
  </ul>
  <ul class="navbar-nav ">
  	<li class="nav-item mx-4">
  		{% if user.is_authenticated %}
  			<div class="nav-link">Welcome {{ request.user.username }}</div>
		{% else %}
        <a class="nav-link" href="{% url 'analytics:login' %}">
          Login
        </a>
        {% endif %}
      </li>
      <li class="nav-item mx-4">
        <a class="nav-link" href="{% url 'analytics:register_user' %}">
          Register
        </a>
      </li>
  </ul>
  </div>
</nav>
</header> -->

dataProcessor/templates/dataProcessor/header.html
{% load static %}
<!-- start: header -->
			<header class="header">
				<div class="logo-container">
						<!-- <img src="{% static 'analytics/assets/images/logo.png' %}" height="35" alt="JSOFT Admin" /> -->
						<a href="{% url 'dataProcessor:index' %}" class="logo">
							<img src="{% static 'analytics/images/companyicon.jpeg' %}" height="35" alt="Geomining" />
						</a>
					<div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
						<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
					</div>
				</div>
			
				<!-- start: search & user box -->
				<div class="header-right">
			
					<form action="pages-search-results.html" class="search nav-form">
						<div class="input-group input-search">
							<input type="text" class="form-control" name="q" id="q" placeholder="Search...">
							<span class="input-group-btn">
								<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
							</span>
						</div>
					</form>
			
					<span class="separator"></span>
			
					{% include "analytics/dashboard/notifications.html" %}
			
					<span class="separator"></span>
			
					<div id="userbox" class="userbox">
						<a href="#" data-toggle="dropdown">
							<figure class="profile-picture">
								<img src="{% static 'analytics/assets/images/!logged-user.jpg' %}" alt="Joseph Doe" class="img-circle" data-lock-picture="{% static 'analytics/assets/images/!logged-user.jpg' %}" />
							</figure>
							<div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@JSOFT.com">
								{% if user.is_authenticated %}
  									<span class="name">{{ request.user.username }}</span>
  									<span class="role">administrator</span>
								{% else %}
        						<a class="nav-link" href="{% url 'analytics:login' %}">
        						  Login
        						</a>
        						{% endif %}
							</div>
			
							<i class="fa custom-caret"></i>
						</a>
			
						<div class="dropdown-menu">
							<ul class="list-unstyled">
								<li class="divider"></li>
								<li>
									<a role="menuitem" tabindex="-1" href="#"><i class="fa fa-user"></i> My Profile</a>
								</li>
								<!-- <li>
									<a role="menuitem" tabindex="-1" href="#" data-lock-screen="true"><i class="fa fa-lock"></i> Lock Screen</a>
								</li> -->
								<li>
									<a role="menuitem" tabindex="-1" href="{% url 'analytics:logout' %}"><i class="fa fa-power-off"></i> Logout</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- end: search & user box -->
			</header>
			<!-- end: header -->

dataProcessor/templates/dataProcessor/index.html
{% extends "dataProcessor/template.html" %}

{% load static %}

{% block content %}
<body>
	<!-- <div class="container-fluid form-container"> -->
		<section class="panel">
			<div class="panel-body">
				<div class="container">
					<div class="row">
						{% for module in modules %}
							{% if module.priority > 2 %}
								<div class="col-lg-2 col-sm-6 col-6 mt-3">
									<div class="card carded-modules">
										<a href="{% url 'dataProcessor:get_template' module=module.module_name %}"></a>
										<span class="centerDiv"><i class="fa {{ module.icon }} fa-2x" style="color: #73c6b6;" aria-hidden="true"></i><br/>{{ module.description }}</span>
									</div>
								</div>
							{% endif %}
						{% endfor %}
					</div>
					<hr>
					<div class="row mt-2">
						{% for module in modules %}
							{% if module.priority < 3 %}
						<div class="col-lg-2 col-sm-6 col-6 mt-3">
							<div class="card carded-modules">
								<a href="{% url 'dataProcessor:get_template' module=module.module_name %}"></a>
								<span class="centerDiv"><i class="fa {{ module.icon }} fa-2x" style="color: #73c6b6;" aria-hidden="true"></i><br/>{{ module.description }}</span>
							</div>
						</div>
							{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
		</section>
	<!-- </div> -->
</body>
{% endblock %}

dataProcessor/templates/dataProcessor/template.html
{% load static %}
{% include "dataProcessor/head.html" %}

<body>
	<input type="hidden" id="baseUrl" value="http://geominingems.com">
	<!-- <input type="hidden" id="baseUrl" value="https://d12m8zkkfoc9oy.cloudfront.net"> -->
		<!-- <input type="hidden" id="baseUrl" value="http://localhost:8002"> -->
		<section class="body">

			{% include "analytics/dashboard/header.html" %}

			<div class="inner-wrapper">
				<!-- {% include "dataProcessor/sidebar.html" %} -->

				<section role="main" class="content-body">
					<header class="page-header">
						<h2>Home</h2>
					
						<div class="right-wrapper pull-right">
							<ol class="breadcrumbs">
								<li>
									<a href="{% url 'dataProcessor:index' %}">
										<i class="fa fa-home"></i>
									</a>
								</li>
								<li><span>Home</span></li>
							</ol>
					
							<a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
						</div>
					</header>

					<div id="content">
        				{% block content %}{% endblock %}
    				</div>
					<hr/>
				</section>
				{% include "analytics/dashboard/footer_nav.html" %}
			</div>

			{% include "analytics/dashboard/calendar.html" %}
		</section>
	</body>
{% include "dataProcessor/footer.html" %}