analytics/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import verify_jwt_token

from . import views
from .view_controllers import index
from .view_controllers import dashboard
from .view_controllers import report_exports
from .view_controllers import saveForms
from .view_controllers import loginAPI

app_name = 'analytics'

# router = routers.DefaultRouter()
# router.register(r'', dashboard.DashboardViewSet, basename='get-details')

router = routers.DefaultRouter()
router.register(r'add_task', views.Add_task, basename='add_task')
router.register(r'update-graph-config', views.Update_graph, basename='update-graph-config')
router.register(r'post-request', saveForms.postRequestViewSet, basename='post-request')
router.register(r'get-reports', dashboard.GetReportsViewSet, basename='get-reports')
router.register(r'add_to_report', index.addToReportViewSet, basename='add_to_report')
router.register(r'save_notes', index.saveNotesViewSet, basename='save_notes')
router.register(r'save_report_structure', index.updateReportViewSet, basename='save_report_structure')
# router.register(r'authenticate-user', loginAPI.loginViewSet_s, basename='authenticate-user')

urlpatterns = [
    path('', index.index, name='index'),
    path('api/', include(router.urls)),
    # path('authenticate-user/', include('rest_auth.urls')),
    # path('update/', include(router.urls)),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('add_task', views.add_task, name='add_task'),
    path('dashboard', index.dashboard, name='dashboard'),
    path('documentation', index.documentation, name='documentation'),
    path('admin-documentation', index.admin_documentation, name='admin-documentation'),
    path('inputter-documentation', index.inputter_documentation, name='inputter-documentation'),
    path('login', index.login, name='login'),
    path('logout', index.logout_user, name='logout'),
    path('media', index.media, name='media'),
    path('add_folder', index.add_folder, name='add_folder'),
    path('add_to_folder', index.add_to_folder, name='add_to_folder'),
    path('add_to_report', index.add_to_report, name='add_to_report'),
    path('delete_images', index.delete_images, name='delete_images'),
    path('delete_folder', index.delete_folder, name='delete_folder'),
    path('delete_graph', index.delete_graph, name='delete_graph'),
    path('delete_table', index.delete_table, name='delete_table'),
    path('save_graph', index.save_graph, name='save_graph'),
    path('graph-builder', index.graph_builder, name='graph-builder'),
    path('report-builder', index.report_builder, name='report-builder'),
    path('table-builder', index.table_builder, name='table-builder'),
    path('get-tables/', dashboard.GetTablesViewSet.as_view(), name='get-tables'),
    path('get-table/', dashboard.GetTableViewSet.as_view({'get': 'retrieve'}), name='get-table'),
    path('get-report/', dashboard.GetReportViewSet.as_view({'get': 'retrieve'}), name='get-report'),
    path('get-notes/', dashboard.GetNotesViewSet.as_view({'get': 'retrieve'}), name='get-notes'),
    path('component_values',views.component_values, name='component_values'),
    path('reports',views.reports_f, name='reports'),
    path('graphs',views.graphs, name='graphs'),
    path('tables',views.tables, name='tables'),
    path('view-graph', views.GetUsers.as_view(), name='view-graph'),
    path('view_table/<module>/<report_id>/',views.view_table, name='view_table'),
    path('view_report/<report_id>/',views.view_report, name='view_report'),
    path('view_all_reports/<module>/',views.view_all_reports, name='view_all_reports'),
    path('register_user', index.registerUser, name='register_user'),
    path('add-user', index.adduser, name='add-user'),
    path('add_report', index.add_report, name='add_report'),
    path('edit-user', index.edituser, name='edit-user'),
    path('schedule_task', index.adduser, name='schedule_task'),
    path('get-details/', dashboard.DashboardViewSet.as_view(), name='get-details'),
    path('get-notifications/', dashboard.NotificationsViewSet.as_view(), name='get-notifications'),
    path('get-users/', views.GetUsers.as_view(), name='get-users'),
    path('/dataProcessor/',include('dataProcessor.urls')),
    path('get-module-details/', dashboard.buildGraphViewSet.as_view(), name='get-module-details'),
    path('get-modules/', index.getModulesViewSet.as_view({'get': 'retrieve'}), name='get-modules'),
    path('get-reports/', dashboard.GetReportsViewSet.as_view({'get': 'retrieve'}), name='get-reports'),
    path('post-request/', saveForms.postRequestViewSet, name='post-request'),
    path('download-documentation/', index.download_pdf_file, name='download-documentation'),
    path('authenticate-user/login/', loginAPI.loginViewSet_s.as_view(), name='authenticate-user'),
    # path(r'^export/csv$', report_exports.export_single_report, name='export_report'),
    path(r'^export/csv/$', report_exports.export_report, name='export_report'),
    path(r'authenticate-user/user/login/', obtain_jwt_token),
    path(r'api-token-verify/', verify_jwt_token),
]

dataAnalytics/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from rest_framework.authtoken.views import obtain_auth_token

from . import view

urlpatterns = [
    path('', view.index, name='index'),
	path('analytics/', include('analytics.urls')),
	path('dataProcessor/',include('dataProcessor.urls')),
    path('api/',include('dataProcessor.urls')),
    path('update/',include('analytics.urls')),
    path(r'^admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth')
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

dataProcessor/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views
from .view_controllers import Storage_facility
from .view_controllers import Grease_and_hydrogen
from .view_controllers import Waste_management
from .view_controllers import Inceneration
from .view_controllers import Liquid_waste_oil
from .view_controllers import Health_and_hygiene
from .view_controllers import Energy_management
from .view_controllers import Water_management
from .view_controllers import Complaints_register
from .view_controllers import Slope_stabilization_and_surface_water_retention
from .view_controllers import Safety_training
from .view_controllers import Safety_permission_system
from .view_controllers import Safety_tools
from .view_controllers import ImageUploader
from .view_controllers import geo_reference
from .view_controllers import FuelFarm
from .view_controllers import WorkEnvCompliance
from .view_controllers import Warehouse
from .view_controllers import Conveyers
from .view_controllers import IncidentReport
from analytics.view_controllers import formulate_report
from .view_controllers import index

app_name = 'dataProcessor'

router = routers.DefaultRouter()
router.register(r'add-seepage', Storage_facility.Storage_facilityViewSet, basename='add-seepage')
router.register(r'add-grease-and-hydrocarbon', Grease_and_hydrogen.Grease_and_hydrogenViewSet, basename='add-grease-and-hydrocarbon')
router.register(r'add-waste-management', Waste_management.Waste_managementViewSet, basename='add-waste-management')
router.register(r'add-inceneration', Inceneration.IncenerationViewSet, basename='add-inceneration')
router.register(r'add-liquid-waste-oil', Liquid_waste_oil.liquid_waste_oilViewSet, basename='add-liquid-waste-oil')
router.register(r'add-health-and-hygiene-awareness', Health_and_hygiene.Health_and_hygieneViewSet, basename='add-health-and-hygiene-awareness')
router.register(r'add-energy-management', Energy_management.Energy_managementViewSet, basename='add-energy-management')
router.register(r'add-water-management', Water_management.Water_managementViewSet, basename='add-water-management')
router.register(r'add-complaints-register', Complaints_register.Complaints_registerViewSet, basename='add-complaints-register')
router.register(r'add-slope-stabilization', Slope_stabilization_and_surface_water_retention.Slope_stabilization_and_surface_water_retentionViewSet, basename='add-slope-stabilization')
router.register(r'add-safety-training', Safety_training.Safety_trainingViewSet, basename='add-safety-training')
router.register(r'add-safety-permission-system', Safety_permission_system.Safety_permission_systemViewSet, basename='add-safety-permission-system')
router.register(r'add-safety-tools', Safety_tools.Safety_toolsViewSet, basename='add-safety-tools')
router.register(r'add-reference-point', geo_reference.Geo_referenceViewSet, basename='add-reference-point')
router.register(r'add-fuel-farm-data', FuelFarm.FuelFarmViewSet, basename='add-fuel-farm-data')
router.register(r'add-work-environmental-compliance-data', WorkEnvCompliance.WorkEnvComplianceViewSet, basename='add-work-environmental-compliance-data')
router.register(r'add-warehouse-data', Warehouse.WarehouseViewSet, basename='add-warehouse-data')
router.register(r'add-conveyers-data', Conveyers.ConveyersViewSet, basename='add-conveyers-data')
router.register(r'add-incident-report', IncidentReport.IncidentReportViewSet, basename='add-incident-report')
router.register(r'build-table', formulate_report.formulateReportViewSet, basename='build-table')
router.register(r'save-table', formulate_report.saveTableViewSet, basename='save-table')
router.register(r'upload_image', ImageUploader.ImageUploader, basename='upload_image')


urlpatterns = [
    path('', index.index, name='index'),
    path('add/', include(router.urls)),
    path('get_template/<module>/',views.get_template, name='get_template'),
    path('grease-and-hydrocarbon', views.grease_and_hydrocarbonView, name='grease-and-hydrocarbon'),
    path('waste-management', views.waste_managementView, name='waste-management'),
    path('inceneration', views.incenerationView, name='inceneration'),
    path('liquid-waste-oil', views.liquid_waste_oilView, name='liquid-waste-oil'),
    path('health-and-hygiene-awareness', views.health_and_hygiene_awarenessView, name='health-and-hygiene-awareness'),
    path('energy-management', views.energy_managementView, name='energy-management'),
    path('water-management', views.water_managementView, name='water-management'),
    path('complaints-register', views.complaints_registerView, name='complaints-register'),
    path('slope-stabilization', views.slope_stabilizationView, name='slope-stabilization'),
    path('safety-training', views.safety_trainingView, name='safety-training'),
    path('safety-permission-system', views.safety_permission_systemView, name='safety-permission-system'),
    path('safety-tools', views.safety_toolsView, name='safety-tools'),
    path('storage-facility', views.storage_facilityView, name='storage-facility'),
    path('geo-reference', views.geoReferenceView, name='geo-reference'),
    path('fuel-farm', views.fuelFarmView, name='fuel-farm'),
    path('work-environment-compliance', views.workEnvComplianceView, name='work-environment-compliance'),
    path('warehouse', views.warehouseView, name='warehouse'),
    path('conveyers', views.conveyersView, name='conveyers'),
    path('incident-report', views.incidentReportView, name='incident-report'),
    # path('/analytics/',include('analytics.urls')),
    # path('add', views.Storage_facilityViewSet, name='add'),
]


# urlpatterns += router.urls

analytics/forms.py
from django import forms

class loginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(widget = forms.PasswordInput())

class indexloginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(widget = forms.PasswordInput())

class registerForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    email = forms.CharField(label='Email', max_length=100, widget= forms.EmailInput(attrs={'class':'form-control',}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control',}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control',}))
    first_name = forms.CharField(label='First Name', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    last_name = forms.CharField(label='Last Name', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    # is_staff = forms.BooleanField(required=False)

class editForm(forms.Form):
    # username = forms.CharField(label='Username', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    email = forms.CharField(label='Email', max_length=100, widget= forms.EmailInput(attrs={'class':'form-control',}))
    first_name = forms.CharField(label='First Name', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    last_name = forms.CharField(label='Last Name', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    # is_staff = forms.BooleanField(required=False)

analytics/templates/analytics/landingpage/footer.html
{% load static %}
<footer class="footerpt-lg-8 pb-9">
	<div class="container">
        <div class="row text-center">
          <div class="col-12">
            <!-- DO NOT DELETE THIS CREDIT. TO DELETE, PLEASE BUY PRO LICENSE -->
            <p class="font-size-4 letter-spacing-np64 line-height-reset mb-0"> &copy; GeoMining Consultancy 2021 All right reserved. </p>
          </div>
        </div>
        <div class="row mt-4">
          <span class="mx-auto">
            <a href="{% url 'analytics:index' %}" class="logo">
              <img src="{% static 'analytics/images/groupicon.jpeg' %}" height="75" alt="Geomining" />
            </a>
          </span>
        </div>
      </div>
</footer>
<script src="{% static 'analytics/js/vendor.min.js' %}"></script>
  <!-- Plugin's Scripts -->
  <script src="{% static 'analytics/plugins/fancybox/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'analytics/plugins/nice-select/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'analytics/plugins/aos/aos.min.js' %}"></script>
  <script src="{% static 'analytics/plugins/slick/slick.min.js' %}"></script>
  <script src="{% static 'analytics/./plugins/counter-up/jquery.waypoints.js' %}"></script>
  <script src="{% static 'analytics/./plugins/counter-up/jquery.counterup.js' %}"></script>
  <script src="{% static 'analytics/plugins/theme-mode-switcher/gr-theme-mode-switcher.js' %}"></script>
  <!-- Activation Script -->
  <script src="{% static 'analytics/js/custom.js' %}"></script>
</body>
</html>

analytics/templates/analytics/landingpage/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>GeoMining Consultancy</title>
  <link rel="shortcut icon" href="{% static 'analytics/image/png/favicon.png' %}" type="image/x-icon">
  <!-- Bootstrap , fonts & icons  -->
  <link rel="stylesheet" href="{% static 'analytics/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'analytics/fonts/icon-font/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'analytics/fonts/typography-font/typo.css' %}">
  <link rel="stylesheet" href="{% static 'analytics/fonts/typography-font/lucida-grande/typo.css' %}">
  <link rel="stylesheet" href="{% static 'analytics/fonts/fontawesome-5/css/all.css' %}">
  <!-- Plugin'stylesheets  -->
  <link rel="stylesheet" href="{% static 'analytics/plugins/aos/aos.min.css' %}">
  <link rel="stylesheet" href="{% static 'analytics/plugins/fancybox/jquery.fancybox.min.css' %}">
  <link rel="stylesheet" href="{% static 'analytics/plugins/nice-select/nice-select.min.css' %}">
  <link rel="stylesheet" href="{% static 'analytics/plugins/slick/slick.min.css' %}">
  <!-- Vendor stylesheets  -->
  <link rel="stylesheet" href="{% static 'analytics/plugins/theme-mode-switcher/switcher-panel.css' %}">
  <link rel="stylesheet" href="{% static 'analytics/css/main.css' %}">
  <!-- Custom stylesheet -->

</head>

<body data-theme="light">
  <div class="site-wrapper overflow-hidden">
    <!-- Header start  -->
    <!-- Header Area -->
    <header class="site-header site-header--menu-left sticky-bg-white light-mode-texts menu-link-hover-dodgerblue site-header--absolute site-header--sticky">
      <div class="container">
        <nav class="navbar site-navbar offcanvas-active navbar-expand-lg px-0">
          <!-- Brand Logo-->
          <div class="brand-logo d-inline-block">
              <!-- light version logo (logo must be black)-->
              <!-- <img src="{% static 'analytics/images/png/logo-blue.png' %}" alt=""> -->
              <a href="{% url 'analytics:index' %}" class="logo">
                <img src="{% static 'analytics/images/companyicon.jpeg' %}" height="35" alt="Geomining" />
              </a>

              <a href="{% url 'analytics:index' %}" class="logo" style="padding-left: 40px;">
                <img src="{% static 'analytics/images/groupicon.jpeg' %}" height="35" alt="Kingho" />
            </a>
              <!-- Dark version logo (logo must be White)-->
          </div>
          <div class="collapse navbar-collapse" id="mobile-menu">
            <div class="navbar-nav-wrapper">
              <ul class="navbar-nav main-menu">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle gr-toggle-arrow" id="navbarDropdown" href="{% url 'analytics:dashboard' %}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Home <i class="icon icon-small-down"></i></a>
                  <ul class="gr-menu-dropdown dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if user.is_staff == 1 %}
                    <li class="drop-menu-item">
                      <a href="{% url 'analytics:dashboard' %}">
                        Dashboard
                      </a>
                    </li>
                    <li class="drop-menu-item">
                      <a href="{% url 'analytics:reports' %}">
                        Reports
                      </a>
                    </li>
                    <li class="drop-menu-item">
                      <a href="{% url 'analytics:media' %}">
                        Media
                      </a>
                    </li>
                    {% else %}
                    <li class="drop-menu-item">
                      <a href="{% url 'dataProcessor:index' %}">
                        Input data
                      </a>
                    </li>
                    {% endif %}
                  </ul>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#" role="button" aria-expanded="false">Support</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'analytics:documentation' %}" role="button" aria-expanded="false">Manual</a>
                </li>
              </ul>
            </div>
            <button class="d-block d-lg-none offcanvas-btn-close" type="button" data-toggle="collapse" data-target="#mobile-menu" aria-controls="mobile-menu" aria-expanded="true" aria-label="Toggle navigation">
              <i class="gr-cross-icon"></i>
            </button>
          </div>
          {% if user.is_authenticated %}
            Welcome, {{ request.user.username }}
          {% else %}
          <div class="header-btns ml-auto pr-2 ml-lg-9 d-none d-xs-flex">
            <a class="btn btn-transparent btn-small border border-mineshaft font-size-5 letter-spacing-n1 font-weight-normal heading-default-color focus-reset mr-lg-6 mr-lg-0 mr-6" href="{% url 'analytics:login' %}">
              Login
            </a>
            <a class="btn btn-lg-1 btn-dodgerblue border border-dodgerblue font-size-5 letter-spacing-n1" href="{% url 'analytics:register_user' %}">
              Register
            </a>
          </div>
          {% endif %}
          <!-- Mobile Menu Hamburger-->
          <button class="navbar-toggler btn-close-off-canvas  hamburger-icon border-0" type="button" data-toggle="collapse" data-target="#mobile-menu" aria-controls="mobile-menu" aria-expanded="false" aria-label="Toggle navigation">
            <!-- <i class="icon icon-simple-remove icon-close"></i> -->
            <span class="hamburger hamburger--squeeze js-hamburger">
          <span class="hamburger-box">
            <span class="hamburger-inner"></span>
            </span>
            </span>
          </button>
          <!--/.Mobile Menu Hamburger Ends-->
        </nav>
      </div>
    </header>

analytics/templates/analytics/landingpage/index.html
{% load static %}
{% include "analytics/landingpage/head.html" %}
<div class="pt-21 pt-sm-24 pt-md-25 pt-lg-30 pb-lg-0 pb-md-9 pb-11 position-relative z-index-1 overflow-hidden">
      <div class="container position-relative">
        <div class="row position-relative justify-content-center">
          <!-- hero area content start -->
          <div class="col-xl-8 col-lg-9 col-md-12 pb-lg-21 pb-md-17 pb-sm-15 pb-10 pr-0" data-aos="fade-left" data-aos-duration="800" data-aos-once="true">
            <!-- hero area section title start -->
            <h1 class="font-size-18 font-family-1 font-wieght-extra-bold heading-default-color letter-spacing-n3 line-height-1p228 mb-11 ">GeoMining Consultancy <br> Company Limited.</h1>
            <!-- hero area section title end -->
            <div class="row">
              <!-- hero area content start -->
              <div class="col-lg-8 col-md-8 col-sm-10 pr-md-6 pr-sm-0">
                <p class="font-size-9 letter-spacing-np4 line-height-1p714 position-relative pr-xl-14 pr-lg-0 pr-md-9 pl-lg-11 pl-9">
                	{% if user.is_authenticated %}
                		You can monitor records and be alerted once any threshold is breached. Simple checkout the dashboard section.
                	{% else %}
                	Login
                	<div class="card login-card">
						<div class="card-body">
							{% block content %}
							<form action="{% url 'analytics:login' %}" class="was-validated"  method="POST" name="form">
  								{% csrf_token %}
  								<table>
									{{ form.as_p }}
								</table>
								<button type="submit" class="btn btn-xl btn-dodgerblue rounder-5 font-size-7 letter-spacing-np9 btn-lg px-lg-9 px-7 py-5 mb-md-0 mb-sm-8">Submit</button>
							</form>
							{% endblock %}
						</div>
					</div>
					{% endif %}
                	<span class="pos-abs-tl px-1 h-50 bg-selago-2"></span> </p>
              </div>
              <!-- hero area content end -->
              <!-- btn start -->
              <div class="col-lg-4 col-md-4 col-sm-6 pl-md-0 pl-sm-12 flex-y-center">
               <!--  <a class="btn btn-xl btn-dodgerblue rounder-5 font-size-7 letter-spacing-np9 btn-lg px-lg-9 px-7 py-5 mb-md-0 mb-sm-8" href="#">Download free trial</a> -->
              </div>
              <!-- btn end -->
            </div>
            <!-- compatible-icon start -->
            <div class="row">
              <div class="col-xl-3 col-lg-4 pr-0 pl-lg-15 pl-sm-12">
                <!-- <div class="pt-7 mt-sm-1 mt-8 border-top d-inline-block">
                  <p class="font-size-5 line-height-reset letter-spacing-np4">Sponsors:</p>
 -->                  <!-- compatible-icon list start -->
                 <!--  <div class="compatible-icon flex-y-center img-grayscale">
                    <a href="#" class="font-size-13 mr-7"><img src="{% static 'analytics/images/l2/svg/windows.svg' %}" alt=""></a>
                    <a href="#" class="font-size-13 mr-7"><img src="{% static 'analytics/images/l2/svg/apple.svg' %}" alt=""></a>
                    <a href="#" class="font-size-13"><img src="{% static 'analytics/images/l2/svg/penguine.svg' %}" alt=""></a>
                  </div> -->
                  <!-- compatible-icon list end -->
                <!-- </div> -->
              </div>
            </div>
            <!-- compatible-icon end -->
          </div>
          <!-- hero area content end -->
        </div>
        <!-- shape-1 start -->
        <div class="pos-abs-bl mb-28 ml-xl-n18 ml-lg-n10 ml-sm-n10 translate-n50 z-index-n1">
          <img src="{% static 'analytics/images/l2/svg/hero-shape-1.svg' %}" alt="" class="animate-1">
        </div>
        <!-- shape-1 end -->
        <!-- shape-2 start -->
        <div class="pos-abs-br mb-lg-5 mr-lg-n18 z-index-n1">
          <img src="{% static 'analytics/images/l2/png/hero-shape-2.png' %}" alt="" class="animate-1">
        </div>
        <!-- shape-2 end -->
      </div>
    </div>

    <div class="pt-21pb-lg-0 pb-md-9 pb-11 position-relative z-index-1 overflow-hidden">
      <div class="container">
        <div class="row position-relative justify-content-center">
          <!-- hero-area content-img start -->
          <div class="col-lg-9" data-aos="zoom-in-left" data-aos-duration="800" data-aos-once="true">
            <img src="{% static 'analytics/images/l2/png/laptop-screen.png' %}" alt="" class="w-100">
          </div>
          <!-- hero-area content-img end -->
        </div>
      </div>
    </div>
</div>



{% include "analytics/landingpage/footer.html" %}