analytics/urls.py
from django.urls import include, path
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import verify_jwt_token

from . import views
from .view_controllers import index
from .view_controllers import dashboard
from .view_controllers import report_exports
from .view_controllers import saveForms
from .view_controllers import loginAPI

app_name = 'analytics'

# router = routers.DefaultRouter()
# router.register(r'', dashboard.DashboardViewSet, basename='get-details')

router = routers.DefaultRouter()
router.register(r'add_task', views.Add_task, basename='add_task')
router.register(r'update-graph-config', views.Update_graph, basename='update-graph-config')
router.register(r'post-request', saveForms.postRequestViewSet, basename='post-request')
router.register(r'get-reports', dashboard.GetReportsViewSet, basename='get-reports')
router.register(r'add_to_report', index.addToReportViewSet, basename='add_to_report')
router.register(r'save_notes', index.saveNotesViewSet, basename='save_notes')
router.register(r'save_report_structure', index.updateReportViewSet, basename='save_report_structure')
# router.register(r'authenticate-user', loginAPI.loginViewSet_s, basename='authenticate-user')

urlpatterns = [
    path('', index.index, name='index'),
    path('api/', include(router.urls)),
    # path('authenticate-user/', include('rest_auth.urls')),
    # path('update/', include(router.urls)),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('add_task', views.add_task, name='add_task'),
    path('dashboard', index.dashboard, name='dashboard'),
    path('documentation', index.documentation, name='documentation'),
    path('admin-documentation', index.admin_documentation, name='admin-documentation'),
    path('inputter-documentation', index.inputter_documentation, name='inputter-documentation'),
    path('login', index.login, name='login'),
    path('logout', index.logout_user, name='logout'),
    path('media', index.media, name='media'),
    path('add_folder', index.add_folder, name='add_folder'),
    path('add_to_folder', index.add_to_folder, name='add_to_folder'),
    path('add_to_report', index.add_to_report, name='add_to_report'),
    path('delete_images', index.delete_images, name='delete_images'),
    path('delete_folder', index.delete_folder, name='delete_folder'),
    path('delete_graph', index.delete_graph, name='delete_graph'),
    path('delete_table', index.delete_table, name='delete_table'),
    path('save_graph', index.save_graph, name='save_graph'),
    path('graph-builder', index.graph_builder, name='graph-builder'),
    path('report-builder', index.report_builder, name='report-builder'),
    path('table-builder', index.table_builder, name='table-builder'),
    path('get-tables/', dashboard.GetTablesViewSet.as_view(), name='get-tables'),
    path('get-table/', dashboard.GetTableViewSet.as_view({'get': 'retrieve'}), name='get-table'),
    path('get-report/', dashboard.GetReportViewSet.as_view({'get': 'retrieve'}), name='get-report'),
    path('get-notes/', dashboard.GetNotesViewSet.as_view({'get': 'retrieve'}), name='get-notes'),
    path('component_values',views.component_values, name='component_values'),
    path('reports',views.reports_f, name='reports'),
    path('graphs',views.graphs, name='graphs'),
    path('tables',views.tables, name='tables'),
    path('view-graph', views.GetUsers.as_view(), name='view-graph'),
    path('view_table/<module>/<report_id>/',views.view_table, name='view_table'),
    path('view_report/<report_id>/',views.view_report, name='view_report'),
    path('view_all_reports/<module>/',views.view_all_reports, name='view_all_reports'),
    path('register_user', index.registerUser, name='register_user'),
    path('add-user', index.adduser, name='add-user'),
    path('add_report', index.add_report, name='add_report'),
    path('edit-user', index.edituser, name='edit-user'),
    path('schedule_task', index.adduser, name='schedule_task'),
    path('get-details/', dashboard.DashboardViewSet.as_view(), name='get-details'),
    path('get-notifications/', dashboard.NotificationsViewSet.as_view(), name='get-notifications'),
    path('get-users/', views.GetUsers.as_view(), name='get-users'),
    path('/dataProcessor/',include('dataProcessor.urls')),
    path('get-module-details/', dashboard.buildGraphViewSet.as_view(), name='get-module-details'),
    path('get-modules/', index.getModulesViewSet.as_view({'get': 'retrieve'}), name='get-modules'),
    path('get-reports/', dashboard.GetReportsViewSet.as_view({'get': 'retrieve'}), name='get-reports'),
    path('post-request/', saveForms.postRequestViewSet, name='post-request'),
    path('download-documentation/', index.download_pdf_file, name='download-documentation'),
    path('authenticate-user/login/', loginAPI.loginViewSet_s.as_view(), name='authenticate-user'),
    # path(r'^export/csv$', report_exports.export_single_report, name='export_report'),
    path(r'^export/csv/$', report_exports.export_report, name='export_report'),
    path(r'authenticate-user/user/login/', obtain_jwt_token),
    path(r'api-token-verify/', verify_jwt_token),
]

dataAnalytics/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from rest_framework.authtoken.views import obtain_auth_token

from . import view

urlpatterns = [
    path('', view.index, name='index'),
	path('analytics/', include('analytics.urls')),
	path('dataProcessor/',include('dataProcessor.urls')),
    path('api/',include('dataProcessor.urls')),
    path('update/',include('analytics.urls')),
    path(r'^admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth')
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

analytics/forms.py
from django import forms

class loginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(widget = forms.PasswordInput())

class indexloginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(widget = forms.PasswordInput())

class registerForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    email = forms.CharField(label='Email', max_length=100, widget= forms.EmailInput(attrs={'class':'form-control',}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={'class':'form-control',}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control',}))
    first_name = forms.CharField(label='First Name', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    last_name = forms.CharField(label='Last Name', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    # is_staff = forms.BooleanField(required=False)

class editForm(forms.Form):
    # username = forms.CharField(label='Username', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    email = forms.CharField(label='Email', max_length=100, widget= forms.EmailInput(attrs={'class':'form-control',}))
    first_name = forms.CharField(label='First Name', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    last_name = forms.CharField(label='Last Name', max_length=100, widget= forms.TextInput(attrs={'class':'form-control',}))
    # is_staff = forms.BooleanField(required=False)

analytics/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from rest_framework import viewsets
from analytics.models import ComplianceValue
from analytics.models import Storage_facility
from analytics.models import Grease_and_hydocarbon_spillage
from analytics.models import Waste_Management
from analytics.models import Inceneration
from analytics.models import Liquid_waste_oil
from analytics.models import Health_and_hygiene_awareness
from analytics.models import Energy_management
from analytics.models import Complaints_register
from analytics.models import Slope_stabilization_and_surface_water_retention
from analytics.models import Safety_training
from analytics.models import Safety_permission_system
from analytics.models import Safety_tools
from analytics.models import Notifications
from analytics.models import NotificationViewer
from analytics.models import WasteDetails
from analytics.models import GeoReferencePoints
from analytics.models import FuelFarm
from analytics.models import WorkEnvCompliance
from analytics.models import Warehouse
from analytics.models import Conveyers
from analytics.models import IncidentReport
from analytics.models import Water_management
from analytics.models import modules
from analytics.models import Image
from analytics.models import Tasks
from analytics.models import Custom_table
from analytics.models import Graph_config
from analytics.models import reports
from analytics.serializers import TasksSerializer
from analytics.serializers import graphConfigSerializer
from analytics.serializers import UsernameSerializer
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from drf_multiple_model.views import ObjectMultipleModelAPIView
from rest_framework.response import Response
from rest_framework import status
import json
import logging
import sys

from analytics.view_controllers.notifications import insert_view_notification


# Get an instance of a logger
logger = logging.getLogger("django")

# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def component_values(request):
	queryset = ComplianceValue.objects.all()
	return render(request, 'analytics/dashboard/component_values.html',{'data':queryset})

def reports_f(request):
	queryset = reports.objects.all()

	querysetm = modules.objects.filter(active=1)

	return render(request, 'analytics/dashboard/reports.html',
		{
			'data':queryset,
			'modules':querysetm})

def graphs(request):
	return render(request, 'analytics/dashboard/graphs.html')

def tables(request):
	queryset = Storage_facility.objects.all().order_by('-created_at')[:4]
	queryset2 = Grease_and_hydocarbon_spillage.objects.all().order_by('-created_at')[:4]
	queryset3 = Waste_Management.objects.all().order_by('-created_at')[:4]
	queryset4 = Inceneration.objects.all().order_by('-created_at')[:4]
	queryset5 = Liquid_waste_oil.objects.all().order_by('-created_at')[:4]
	queryset6 = Health_and_hygiene_awareness.objects.all().order_by('-created_at')[:4]
	queryset7 = Energy_management.objects.all().order_by('-created_at')[:4]
	queryset8 = Complaints_register.objects.all().order_by('-created_at')[:4]
	queryset9 = Slope_stabilization_and_surface_water_retention.objects.all().order_by('-created_at')[:4]
	queryset10 = Safety_training.objects.all().order_by('-created_at')[:4]
	queryset11 = Safety_permission_system.objects.all().order_by('-created_at')[:4]
	queryset12 = Safety_tools.objects.all().order_by('-created_at')[:4]
	queryset13 = GeoReferencePoints.objects.all().order_by('-created_at')[:4]
	queryset14 = FuelFarm.objects.all().order_by('-created_at')[:4]
	queryset15 = WorkEnvCompliance.objects.all().order_by('-created_at')[:4]
	queryset16 = Warehouse.objects.all().order_by('-created_at')[:4]
	queryset17 = Conveyers.objects.all().order_by('-created_at')[:4]
	queryset18 = IncidentReport.objects.all().order_by('-created_at')[:4]
	queryset19 = Water_management.objects.all().order_by('-created_at')[:4]

	custom_tables = Custom_table.objects.filter(active=1)

	querysetm = modules.objects.filter(active=1)

	return render(request, 'analytics/dashboard/tables.html',
		{
			'custom_tables':custom_tables,
			'data1':queryset,
			'data2':queryset2,
			'data3':queryset3,
			'data4':queryset4,
			'data5':queryset5,
			'data6':queryset6,
			'data7':queryset7,
			'data8':queryset8,
			'data9':queryset9,
			'data10':queryset10,
			'data11':queryset11,
			'data12':queryset12,
			'data13':queryset13,
			'data14':queryset14,
			'data15':queryset15,
			'data16':queryset16,
			'data17':queryset17,
			'data18':queryset18,
			'data19':queryset19,
			'modules':querysetm})

def str_to_class(str):
    return getattr(sys.modules[__name__], str)

def view_table(request, module, report_id):
	if request.user.is_authenticated:
		user = request.user
		reportid = report_id
		module = module
		modules_queryset = modules.objects.filter(active=1)
		
		url = 'analytics/dashboard/view_table.html'
	
		# queryset = modules.objects.filter(id=module)
		# module = queryset[0].module_name
		if module=="custom":
			queryset = reportid
			url = 'analytics/dashboard/custom_table_view.html'
			module = 0
		else:
			myModel = Storage_facility
		
			for module_i in modules_queryset.values():
				if int(module) == module_i['id']:
					myModel = str_to_class(module_i['table'])
					logger.info(" Matches!! ")
					logger.info(module_i['table'])
		
			
		
			queryset = myModel.objects.filter(report_name=reportid)
		
			logger.info("Queryset is ")
			logger.info(queryset)
			# logger.info("And report ID is ")
			# logger.info(reportid)
	
			# try:
			insert_view_notification(user,reportid,module)
			# except:
			# 	logger.info("No notification sent ")

		modules_queryset_single = modules.objects.filter(id=module)
		image_queryset = Image.objects.filter(report_id=reportid, module_id__in=modules_queryset_single.values('id'))
	
		return render(request, url,{'report_data':queryset,'module':int(module),'modules':modules_queryset,'images':image_queryset})
	else:
		return HttpResponseRedirect('login')

def view_report(request, report_id):
	if request.user.is_authenticated:
		user = request.user
		reportid = report_id

		modules_queryset = modules.objects.filter(active=1)
		
		url = 'analytics/dashboard/view_report.html'
	
		return render(request, url,{'report_id':reportid,'modules':modules_queryset})
	else:
		return HttpResponseRedirect('login')

def view_all_reports(request, module):
	module = module

	modules_queryset = modules.objects.filter(active=1)

	myModel =  Custom_table
	url = 'analytics/dashboard/custom_tables_all.html'

	for module_i in modules_queryset.values():
			if module == module_i['module_name']:
				myModel = str_to_class(module_i['table'])
				url = 'analytics/dashboard/reports_all_records.html'

	queryset13 = modules.objects.filter(active=1)

	queryset = myModel.objects.filter(active=1)

	return render(request, url,{'data':queryset,'module':module, 'modules':queryset13})

def add_task(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			user = request.user

			task_for = request.user.username

			if request.POST['task_for']!="self":
				task_for = User.objects.get(username=request.POST['task_for'])
				task_for = task_for.username


			task_save = Tasks(
				task=request.POST['task'],
				description=request.POST['description'],
				start_time=request.POST['start_time'],
				end_time=request.POST['end_time'],
				created_by=user,
				task_for=task_for
			)
			task_save.save()
			return redirect(request.META['HTTP_REFERER'])
		else:
			return redirect(request.META['HTTP_REFERER'])
	else:
		return HttpResponseRedirect('login')

class Update_graph(viewsets.ViewSet):
	def create(self, request):
		serializer = graphConfigSerializer(data=request.data)

		if serializer.is_valid(raise_exception=True):
			graph_config = Graph_config.objects.get(id=int(serializer.data['id']))
			on_dashboard = True
			if serializer.data['value'] == 'true':
				on_dashboard=True
			else:
				on_dashboard=False

			graph_config.on_dashboard = on_dashboard
			graph_config.save()
	
			return Response("updated",status=status.HTTP_202_ACCEPTED)
		else:
			return Response(status=status.HTTP_400_BAD_REQUEST)



class GetUsers(ObjectMultipleModelAPIView):
	querylist=[
			{'queryset': User.objects.filter(is_active=1), 'serializer_class': UsernameSerializer},
	]

class Add_task(viewsets.ViewSet):
	def create(self, request):
		serializer = TasksSerializer(data=request.data)

		# user = User.objects.get(username=serializer.data['username'])
		# created_by_id = user.id

analytics/templates/analytics/dashboard/adduser.html
{% extends "analytics/dashboard/template.html" %}

{% load static %}

{% block main_content %}
	<div class="container-fluid">
		<section class="body-sign">
			<div class="center-sign">
				<a href="{% url 'analytics:index' %}" class="logo pull-left">
                <img src="{% static 'analytics/images/companyicon.jpeg' %}" height="35" alt="Geomining" />
                <br>
				GeoMining Consultancy Company Limited
              </a>

				<div class="panel panel-sign">
					<div class="panel-title-sign mt-xl text-right">
						<h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i> Add User</h2>
					</div>
					<div class="panel-body">
						<form action="{% url 'analytics:add-user' %}" class="was-validated"  method="POST" name="form">
							{% csrf_token %}
							{% if error_message %}
                    	        <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        	{% endif %}
  							{% block content %}
  									{% csrf_token %}
  									<table>
					  					{{ form.as_table }}
					  				</table>

					  				<div class="form-check form-check-inline">
  										<input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="" name="admin_user_check">
  										<label class="form-check-label" for="inlineCheckbox1">Admin User</label>
									</div>
							{% endblock %}

							<div class="row">
								<div class="col-sm-8">
									<!-- <div class="checkbox-custom checkbox-default">
										<input id="AgreeTerms" name="agreeterms" type="checkbox"/>
										<label for="AgreeTerms">I agree with <a href="#">terms of use</a></label>
									</div> -->
								</div>
								<div class="col-sm-4 text-right">
									<button type="submit" class="btn btn-primary hidden-xs">Save</button>
									<button type="submit" class="btn btn-primary btn-block btn-lg visible-xs mt-lg">Save</button>
								</div>
							</div>

							<span class="mt-lg mb-lg line-thru text-center text-uppercase">
								<span>o</span>
							</span>

							<!-- <div class="mb-xs text-center">
								<a class="btn btn-facebook mb-md ml-xs mr-xs">Connect with <i class="fa fa-facebook"></i></a>
								<a class="btn btn-twitter mb-md ml-xs mr-xs">Connect with <i class="fa fa-twitter"></i></a>
							</div> -->

						</form>
					</div>
				</div>

				<p class="text-center text-muted mt-md mb-md">&copy; Copyright 2021. All rights reserved. GeoMining Consultancy.</p>
			</div>
		</section>

	</div>

	<script src="{% static 'graphbuilder-bundle.js' %}"></script>
{% endblock %}

analytics/templates/analytics/dashboard/custom_tables.html
{% load static %}
<div class="container-fluid">
		<section class="panel">
			<header class="panel-heading">
				<div class="panel-actions">
					<a href="#" class="fa fa-caret-down"></a>
					<!-- <a href="#" class="fa fa-times"></a> -->
				</div>
		
				<h2 class="panel-title">Custom Tables</h2>
			</header>
			<div class="panel-body">
				<table class="table table-bordered table-striped mb-none" id="datatable-details">
					<thead>
						<tr>
							<th>Report Name</th>
							<th>Description</th>
							<th>Report Date</th>
						</tr>
					</thead>
					<tbody>
						{% for table in custom_tables %}
						<tr class="grade">
							<td><a class="row-link" href="{% url 'analytics:view_table' report_id=table.id module='custom' %}">{{ table.table_name }}</a></td>
							<td>{{ module.description }}</td>
							<td>{{ table.created_at }}</td>
						</tr>
						{% endfor %}
						<tr class="grade"><td colspan="2" style="border: none;"><a href="{% url 'analytics:view_all_reports' module='custom' %}" class="btn btn-outline-danger">View all</a></td>
						</tr>
					</tbody>
				</table>
			</div>
		</section>
	</div>

analytics/templates/analytics/dashboard/edituser.html
{% extends "analytics/dashboard/template.html" %}

{% load static %}

{% block main_content %}
	<div class="container-fluid">
		<div class="row">
		<div class="col-lg-3" style="max-height: 90vh; overflow-y: scroll;">
			<section class="body-sign">
				<div class="center-sign">
					{% for user in users %}
						<button type="button" class="edit_user_btn btn btn-primary btn-block">{{ user.username }}
							<input type="hidden" class="username" value="{{ user.username }}">
							<input type="hidden" class="email" value="{{ user.email }}">
							<input type="hidden" class="first_name" value="{{ user.first_name }}">
							<input type="hidden" class="last_name" value="{{ user.last_name }}">
						</button>
					{% endfor %}
				</div>
			</section>
		</div>
		<div class="col-lg-9">
			<section class="body-sign">
				<div class="center-sign">
					<a href="{% url 'analytics:index' %}" class="logo pull-left">
        	        <img src="{% static 'analytics/images/companyicon.jpeg' %}" height="35" 	alt="Geomining" />
        	        <br>
					GeoMining Consultancy Company Limited
        	      </a>
	
					<div class="panel panel-sign">
						<div class="panel-title-sign mt-xl text-right">
							<h2 class="title text-uppercase text-bold m-none"><i class="fa fa-user mr-xs"></i> Edit User</h2>
						</div>
						<div class="panel-body">
							<form action="{% url 'analytics:edit-user' %}" class="was-validated edit_form"  method="POST" name="form">
								<input type="hidden" name="username" class="username_f" value="{{ edit_username }}">
								<input type="hidden" name="action" class="action" value="">
								{% if error_message %}
        	            	        <p class="bg-danger p-d ml-b">{{ error_message }}</p>
        	                	{% endif %}
  								{% block content %}
  										{% csrf_token %}
  										<table>
						  					{{ form.as_table }}
						  				</table>
								{% endblock %}
	
								<div class="row mt-4">
									<div class="col-sm-6">
										
									</div>

									<div class="col-sm-3 text-right">
										<button type="submit" class="btn btn-primary 	hidden-xs save_btn">Save</button>
										<button type="submit" class="btn btn-primary 	btn-block btn-lg visible-xs mt-lg save_btn">Save</button>
									</div>

									<div class="col-sm-3 text-right">
										<button type="submit" class="btn btn-danger 	hidden-xs delete_btn">Delete</button>
										<button type="submit" class="btn btn-danger 	btn-block btn-lg visible-xs mt-lg delete_btn">Delete</button>
									</div>
								</div>
	
								<span class="mt-lg mb-lg line-thru text-center text-uppercase">
									<span>o</span>
								</span>
								<!-- <div class="mb-xs text-center">
									<a class="btn btn-facebook mb-md ml-xs mr-xs">Connect 	with <i class="fa fa-facebook"></i></a>
									<a class="btn btn-twitter mb-md ml-xs mr-xs">Connect with <i class="fa fa-twitter"></i></a>
								</div> -->
							</form>
						</div>
					</div>
	
					<p class="text-center text-muted mt-md mb-md">&copy; Copyright 2021. All rights reserved. GeoMining Consultancy.</p>
				</div>
			</section>
		</div>
		</div>
	</div>

	<script src="{% static 'graphbuilder-bundle.js' %}"></script>
{% endblock %}

analytics/templates/analytics/dashboard/graphs.html
{% extends "analytics/dashboard/template.html" %}

{% load static %}

{% block main_content %}
	<input type="hidden" name="module_name" id="module" value="all">
	<div id="report-graphs"></div>

    <script src="{% static 'report-bundle.js' %}"></script>
{% endblock %}

analytics/templates/analytics/dashboard/header.html
{% load static %}
<!-- start: header -->
			<header class="header">
				<div class="logo-container">
					<a href="{% url 'analytics:index' %}" class="logo">
						<img src="{% static 'analytics/images/companyicon.jpeg' %}" height="35" alt="Geomining" />
					</a> <a href="{% url 'analytics:index' %}" class="logo" style="padding-left: 40px;">
						<img src="{% static 'analytics/images/groupicon.jpeg' %}" height="35" alt="Kingho" />
					</a>
					<div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
						<i class="fa fa-bars" aria-label="Toggle sidebar"></i>
					</div>
				</div>
			
				<!-- start: search & user box -->
				<div class="header-right">
			
					<form action="pages-search-results.html" class="search nav-form">
						<div class="input-group input-search">
							<input type="text" class="form-control" name="q" id="q" placeholder="Search...">
							<span class="input-group-btn">
								<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
							</span>
						</div>
					</form>
			
					<span class="separator"></span>
			
					{% include "analytics/dashboard/notifications.html" %}
			
					<span class="separator"></span>
			
					<div id="userbox" class="userbox">
						<a href="#" data-toggle="dropdown">
							<figure class="profile-picture">
								<img src="{% static 'analytics/assets/images/!logged-user.jpg' %}" alt="Joseph Doe" class="img-circle" data-lock-picture="{% static 'analytics/assets/images/!logged-user.jpg' %}" />
							</figure>
							<div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@JSOFT.com">
								{% if user.is_authenticated %}
  									<span class="name">{{ request.user.username }}</span>
  									<span class="role">administrator</span>
								{% else %}
        						<a class="nav-link" href="{% url 'analytics:login' %}">
        						  Login
        						</a>
        						{% endif %}
							</div>
			
							<i class="fa custom-caret"></i>
						</a>
			
						<div class="dropdown-menu">
							<ul class="list-unstyled">
								<li class="divider"></li>
								<li>
									<a role="menuitem" tabindex="-1" href="#"><i class="fa fa-user"></i> My Profile</a>
								</li>
								{% if user.is_authenticated and request.user.is_staff == 1 %}
								<li>
									<a role="menuitem" tabindex="-1" href="#" data-toggle="modal" data-target="#scheduler"><i class="fa fa-user"></i> Schedule a task</a>
								</li>
								{% endif %}
								<!-- <li>
									<a role="menuitem" tabindex="-1" href="#" data-lock-screen="true"><i class="fa fa-lock"></i> Lock Screen</a>
								</li> -->
								<li>
									<a role="menuitem" tabindex="-1" href="{% url 'analytics:logout' %}"><i class="fa fa-power-off"></i> Logout</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- end: search & user box -->
			</header>
			<!-- end: header -->

analytics/templates/analytics/dashboard/reports_all_records.html
{% extends "analytics/dashboard/template.html" %}

{% load static %}

{% block main_content %}
	<div class="container-fluid">
		{% for module1 in modules %}
			{% if module1.module_name == module %}
			<section class="panel">
				<header class="panel-heading">
					<div class="panel-actions">
						<a href="#" class="fa fa-caret-down"></a>
						<!-- <a href="#" class="fa fa-times"></a> -->
					</div>
			
					<h2 class="panel-title">{{ module1.description }}</h2>
				</header>
				<div class="panel-body">
					<table class="table table-bordered table-striped mb-none" id="datatable-details">
						<thead>
							<tr>
								<th>Report Name</th>
								<th>Report Type</th>
								<th>Report Date</th>
							</tr>
						</thead>
						<tbody>
							{% for value in data %}
							<tr class="grade">
								<td><a class="row-link" href="{% url 'analytics:view_table' report_id=value.report_name module=module1.id %}">{{ value.report_name }}</a></td>
								<td>{{ module1.description }}</td>
								<td>{{ value.created_at }}</td>
							</tr>
							{% endfor %}
							<tr class="grade"><td colspan="2"><a href="{% url 'analytics:view_all_reports' module=module1.module_name %}" class="btn btn-outline-danger">View details</a></td>
							<td colspan="1" style="border: none;"><a href="#" class="btn btn-outline-danger export-all-selected"  data-toggle="modal" data-target="#report-date-selector">Export All</a><input type="hidden" id="module_s" value="{{ module1.module_name }}"></td></tr>
						</tbody>
					</table>
				</div>
			</section>
			{% endif %}
		{% endfor %}

	</div>
{% endblock %}